### ISSUE TITLE
Asteroids should wrap at screen borders

### ISSUE THREAD

**Issue by antont** [reu/bevyroids#2]
Right? Is like that in the original at least.

Maybe this works just by setting `BoundaryWrap` to use for the asteroids?

Am curious because am planning a similar wrapping 2D toy thing, might reuse the systems from here, the code seemed nice for a Rust newbie at least, thanks!

**Comment by reu** [comment]
Hey @antont! Yeah, just add `BoundaryWrap` to the asteroids and it should work fine. I think some versions of the "original" had that and some don't, but I don't remember TBH hahaha

**Comment by reu** [comment]
Closing this for now, but just to let you know that I just tested changing `BoundaryRemoval` with `BoundayWrap` on the asteroids and it worked perfectly!
